### ISSUE TITLE
Removing the nginx-repo cert and key cause nginx-agent install to fail

### ISSUE THREAD

**Issue by gallarda** [leonseng/nginx-acm-aws#3] opened 2023-01-05 23:02 UTC
In #1, the nginx-repo cert and key are removed from the AMI.  This causes the nginx-agent install to fail.

Was an ACM install tested after this PR was integrated? @aknot242

**Comment by aknot242** [comment] 2023-01-05 23:44
@gallarda it could have been a miss 😬. Since the crt + key removal is at the end of the script, my assumption was that everything should be complete. When is the agent installed? On initial bootup of the AMI? And since the agent is open source, are the packages available in a public repo, or only in the nginx private repos? Should definitely avoid creating images that have a crt + key in them. Can you install the agent before packer builds the image? This could also help you avoid installing a version of agent that isn't compatible with NIM + ACM, if the versions installed in the image are older.

**Comment by leonseng** [comment] 2023-01-06 03:45
The agent is installed when the gateways are added on ACM and the curl command executed. This requires ACM to be licensed prior, which happens during the Terraform deployment, not when the image is built via Packer.

I think #1 is a good idea, and to deal with the NGINX agent installation issue post Terraform deployment, I'm thinking we make NGINX repo cert and key as inputs to Terraform as well and load them into the gateways during Terraform deployment.

**Comment by aknot242** [comment] 2023-01-06 14:36
In @codygreen 's implementation, he uses AWS secrets to store the crt + key. Ultimately, these need to be pulled out and pushed to the instances as files, so I'm not sure what the benefit is in that case besides keeping these in state after the files are deleted. Just sharing in case you find a benefit in using them. https://github.com/codygreen/nms_lab_env/blob/8398c3a91786ae129eade1ff0dc294a9200ba9a0/gateway_userdata.tpl#L17

**Comment by leonseng** [comment] 2023-01-08 07:18
Fixed with https://github.com/leonseng/nginx-acm-aws/commit/d7bace2bab7377deba5c6d8714f45e830ab1e4a2 by passing in NGINX repo key/cert as Terraform inputs. AWS Secrets Manager support will be an enhancement for the future

**Closed as completed by leonseng** 2023-01-08 07:18 UTC

**Comment by gallarda** [comment] 2023-01-09 19:54
Passing the NGINX repo cert and key as Terraform inputs (or AWS secrets) is not solving the problem identified in this issue.  You only need NGINX repo access during the Packer build phase.  The AMIs are already built (and nginx installed) before Terraform is invoked.

The problem with @aknot242's PR #1 is that when only the NGINX cert and key are removed it breaks the NGINX repo definition. This prevents the nginx-agent from being installed.

The solution is to also remove the NGINX repo PPA in addition to the cert and key.

I will submit a PR that does this.  @leonseng, please remove that last commit with the Terraform inputs.  We don't want to put the NGINX cert and key back into the VMs because the NGINX software is already installed.

**Comment by aknot242** [comment] 2023-01-09 21:25
Aaah! The issue is clearer now. Thanks @gallarda.
